import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";

import client from "../apollo_client";

export default function Home({data}) {
  console.log(data.getProducts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hello world</h1>
      <div>
        {
          data.getProducts?.length > 0 ? (
            data.getProducts.map(d => <div>{d.name}</div>)
          ) :null
        }
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query GetProducts {
        getProducts {
          id
          name
        }
      }
    `,
  });
  console.log(data);

  return {
    props:{
      data
    }
  }

}
